dataset_attributes:
  m4c_textvqa:
      data_root_dir: /home/ubuntu/hzy/pythia/data
      image_depth_first: false
      fast_read: false
      features_max_len: 100
      processors:
        context_processor:
          type: fasttext
          params:
            max_length: 50
            model_file: /home/ubuntu/hzy/pythia//pythia/models/.vector_cache/wiki.en.bin    
        obj_context_processor:
          type: fasttext
          params:
            max_length: 100
            model_file: /home/ubuntu/hzy/pythia//pythia/models/.vector_cache/wiki.en.bin    
        ocr_token_processor:
          type: simple_word
          params: {}
        bbox_processor:
          type: bbox
          params:
            max_length: 50
      return_info: true
      use_ocr: true
      use_ocr_info: true